server:
  port: 8082

spring:
  application:
    name: service-provider-b
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  pattern:
    level: "%5p [service-provider-b,%X{traceId:-},%X{spanId:-}]"
